stages:
  - build

before_script:
- docker info
- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_HOST

build:
  stage: build
  tags:
    - docker
    - runners
  only:
    - tags
  script:
    - docker build -t $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_TAG -t $REGISTRY_HOST/$CI_PROJECT_PATH:latest .
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_TAG
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH:latest
